from django.conf import settings

from rest_framework import status
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from apps.core.api.views import BaseViewSet

from .serializers import LLMRequestSerializer, LLMResponseSerializer


class AssistanceViewSet(BaseViewSet):
    """View set of operations on LLM."""

    extra_permission_classes = (
        IsAuthenticated,
    )

    @action(detail=False, methods=["POST"])
    def ask_kapi(self, request, *args, **kwargs):
        """Return llm response generated by text."""
        serializer = LLMRequestSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        llm_response =settings.LLM_CHAIN.invoke(
            {"user_message": serializer.validated_data},
        )
        return Response(
            data=LLMResponseSerializer(llm_response).data,
            status=status.HTTP_201_CREATED,
        )
